apiVersion: v1  
kind: Secret  
metadata:  
  name: mysql-secrets
type: Opaque  
data:  
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-user: eWFzaHNhbGVzYQ==
  mysql-password: eWFzaHNhbGVzYTEyMw==
